fix errors and update convert script

diff --git a/rule_conversion/action.yml b/rule_conversion/action.yml
--- a/rule_conversion/action.yml
+++ b/rule_conversion/action.yml
@@ -16,6 +16,27 @@ runs:
         python -m pip install -r ${{ github.action_path }}/requirements.txt
       shell: bash
 
+    - name: Run validation script
+      id: run_validation
+      shell: bash
+      run: |
+            set -o pipefail
+            python ${{ github.action_path }}/validate.py --input-file "${{ inputs.input-file }}" > validation_output.txt || true
+
+            echo "::group::Validation Output"
+            cat validation_output.txt
+            echo "::endgroup::"
+
+            # Export result for GitHub Actions
+            echo "result<<EOF" >> $GITHUB_OUTPUT
+            cat validation_output.txt >> $GITHUB_OUTPUT
+            echo "EOF" >> $GITHUB_OUTPUT
+
+            # Fail the step if validation errors are found
+            if grep -q "Error:" validation_output.txt; then
+              exit 1
+            fi
+    
     - name: Run conversion script
       run: |
         python ${{ github.action_path }}/convert.py --input-file ${{ inputs.input-file }}
